Contacts - mobile
BarZab/team-project-Ice_Cream pull request #10
Opened 2022-05-21 08:54 UTC by KlaudiaK0205

- wersja mobilna sekcji CONTACTS

2022-05-21 10:57 UTC, BarZab requested changes

2022-05-21 10:57 UTC, BarZab commented on src/partials/contacts.html
> +                <p class="contact__item__phone"><a class="contacts__phone link" href="tel:+61(0)383766284">+61(0) 383 766 284</a>
selektor powinien być zapisany jako np. "contacts__item-phone". Dodatkowo występuje literówka bo zamiast contacts masz contact

2022-05-21 10:57 UTC, BarZab commented on src/sass/layout/_contacts.scss
> +.contacts__item__town {
tak samo jak skomentowałem w pliku nie tworzymy selektorów o konstrukcji "rodzic__rodzic__potomek" tylko "rodzic__potomek". można jeszcze utworzyć ewentualnie nowego rodzica, w tym przypadku "item__town" itd

2022-05-22 06:34 UTC, KlaudiaK0205 commented
Naniosłam poprawki zgodnie z Twoim zaleceniem

2022-05-22 15:07 UTC, BarZab approved these changes

2022-05-22 15:07 UTC, merged